package bot.api.dto

case class Message(
message_id: Integer,
message_thread_id: Integer,
from: User,
sender_chat: Chat,
date: Integer,
chat: Chat,
forward_from: User,
forward_from_chat: Chat,
forward_from_message_id: Integer,
forward_signature: String,
forward_sender_name: String,
forward_date: Integer,
is_topic_message: Boolean,
is_automatic_forward: Boolean,
reply_to_message: Message,
via_bot: User,
edit_date: Integer,
has_protected_content: Boolean,
media_group_id: String,
author_signature: String,
text: String,
entities: Array[MessageEntity],
animation: Animation,
audio: Audio,
document: Document,
photo: Array of PhotoSize,
sticker: Sticker,
video: Video,
video_note: VideoNote,
voice: Voice,
caption: String,
caption_entities: Array of MessageEntity,
has_media_spoiler: ИСТИНА,
contact: Contact,
dice: Dice,
game: Game,
poll: Poll,
venue: Venue,
location: Location,
new_chat_members: Array of User,
left_chat_member: User,
new_chat_title: String,
new_chat_photo: Array of PhotoSize,
delete_chat_photo: ИСТИНА,
group_chat_created: ИСТИНА,
supergroup_chat_created: ИСТИНА,
channel_chat_created: ИСТИНА,
message_auto_delete_timer_changed: MessageAutoDeleteTimerChanged,
migrate_to_chat_id: Integer,
migrate_from_chat_id: Integer,
pinned_message: Message,
invoice: Invoice,
successful_payment: SuccessfulPayment,
user_shared: UserShared,
chat_shared: ChatShared,
connected_website: String,
write_access_allowed: WriteAccessAllowed,
passport_data: PassportData,
proximity_alert_triggered: ProximityAlertTriggered,
forum_topic_created: ForumTopicCreated,
forum_topic_edited: ForumTopicEdited,
forum_topic_closed: ForumTopicClosed,
forum_topic_reopened: ForumTopicReopened,
general_forum_topic_hidden: GeneralForumTopicHidden,
general_forum_topic_unhidden: GeneralForumTopicUnhidden,
video_chat_scheduled: VideoChatScheduled,
video_chat_started: VideoChatStarted,
video_chat_ended: VideoChatEnded,
video_chat_participants_invited: VideoChatParticipantsInvited,
web_app_data: WebAppData,
reply_markup: InlineKeyboardMarkup,
)
